[package]
name = "sw-sync-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
toml = "0.8.13"
anyhow = "1.0.86"
csv = "1.3.0"
itertools = "0.13.0"
