[package]
name = "sw-sync-cli"
version = "0.1.0"
edition = "2021"
description = "CLI for fast and flexible data transfer between shopware <-> (CSV) file over API"
keywords = ["cli", "shopware", "import", "export"]
categories = ["command-line-utilities", "development-tools", "web-programming"]
authors = ["Malte Janz <service.malte.j@protonmail.com>"]
license = "MIT"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
serde_yaml = "0.9.33"
toml = "0.8.14"
thiserror = "1.0.61"
anyhow = "1.0.86"
csv = "1.3.0"
itertools = "0.13.0"
rhai = { version = "1.18.0", features = ["serde", "sync"] }
