# Profile for product variants
entity: product

filter:
  # export variant products (parentId != NULL) only
  - type: "not"
    operator: "and"
    queries:
      - type: "equals"
        field: "parentId"
        value: null

mappings:
  - file_column: "id"
    entity_path: "id"
  - file_column: "product number"
    entity_path: "productNumber"
  - file_column: "default name"
    entity_path: "name"
  - file_column: "default price net"
    key: "default_price_net"
  - file_column: "default price gross"
    key: "default_price_gross"
  - file_column: "stock"
    entity_path: "stock"
  - file_column: "tax id"
    entity_path: "taxId"
  # this field is technically not required, but important for variants
  - file_column: "parent id"
    entity_path: "parentId"

serialize_script: |
  let default_currency = get_default("CURRENCY");
  let price = entity.price.find(|p| p.currencyId == default_currency);
  row.default_price_net = price.net;
  row.default_price_gross = price.gross;

deserialize_script: |
  entity.price = [
    #{
      net: row.default_price_net,
      gross: row.default_price_gross,
      linked: true,
      currencyId: get_default("CURRENCY"),
    }
  ];
