# Profile for products together with their manufacturers
# Manufacturers can be modified and imported again
entity: product

filter:
  # export main products (parentId = NULL) only
  - type: "equals"
    field: "parentId"
    value: null

sort:
  - field: "manufacturerId"
    order: "DESC"

mappings:
  - file_column: "id"
    entity_path: "id"
  - file_column: "product number"
    entity_path: "productNumber"
  - file_column: "default name"
    entity_path: "name"
  - file_column: "default price net"
    key: "default_price_net"
  - file_column: "default price gross"
    key: "default_price_gross"
  - file_column: "stock"
    entity_path: "stock"
  - file_column: "tax id"
    entity_path: "taxId"
  - file_column: "manufacturer id"
    entity_path: "manufacturer?.id"
  - file_column: "manufacturer name"
    entity_path: "manufacturer?.name"
  - file_column: "manufacturer website"
    entity_path: "manufacturer?.link"

serialize_script: |
  // ToDo: add convenience function to lookup default currencyId
  let price = entity.price.find(|p| p.currencyId == "b7d2554b0ce847cd82f3ac9bd1c0dfca");
  row.default_price_net = price.net;
  row.default_price_gross = price.gross;

deserialize_script: |
  entity.price = [
    #{
      net: row.default_price_net,
      gross: row.default_price_gross,
      linked: true,
      currencyId: "b7d2554b0ce847cd82f3ac9bd1c0dfca",
    }
  ];
